"""corrected session_speakers table name

Revision ID: 609e714feebd
Revises: 28e95e1d54a9
Create Date: 2026-04-21 18:32:40.821789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609e714feebd'
down_revision = '28e95e1d54a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_speakers',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('speaker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_session_speakers_session_id_sessions')),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], name=op.f('fk_session_speakers_speaker_id_speakers')),
    sa.PrimaryKeyConstraint('session_id', 'speaker_id')
    )
    op.drop_table('sessionspeaker')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessionspeaker',
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('speaker_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_sessionspeaker_session_id_sessions')),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], name=op.f('fk_sessionspeaker_speaker_id_speakers')),
    sa.PrimaryKeyConstraint('session_id', 'speaker_id')
    )
    op.drop_table('session_speakers')
    # ### end Alembic commands ###
